# Generated by Django 4.1.4 on 2022-12-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('director', models.CharField(max_length=500)),
                ('actors', models.CharField(max_length=500)),
                ('plot', models.CharField(max_length=1000)),
                ('posterUrl', models.CharField(max_length=1000)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
