# Generated by Django 4.1.4 on 2022-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='times_review',
            field=models.IntegerField(default=1),
        ),
    ]
