# Generated by Django 4.1.4 on 2022-12-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review_last_modified_review_times_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
