# Generated by Django 4.1.4 on 2022-12-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movielist_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='times_review',
        ),
    ]
