# Generated by Django 4.1.4 on 2022-12-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_review_times_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
